version: "2.1"

services:

  gradle-github-api-v3-gateway-app:
    build:
      context: .
      dockerfile: ./gradle/Dockerfile
    volumes: ["gradle-github-api-v3-gateway-app-data:/home/appuser"]
    networks: [backing-services]
    ports: ["8080:8080"]
    restart: unless-stopped
    mem_limit: 209715200 # container limit: 200Mb (200 * 1024 * 1024)

volumes:
  gradle-github-api-v3-gateway-app-data: {}

networks:
  backing-services:
    driver: bridge
